-- ============================================================
-- OwnPay v0.1.0 - Comprehensive World Currencies Seed Data
-- ============================================================

INSERT INTO `op_currencies` (`code`, `name`, `symbol`, `decimal_places`, `status`) VALUES
('AED', 'United Arab Emirates Dirham', 'د.إ', 2, 'inactive'),
('AFN', 'Afghan Afghani', '؋', 2, 'inactive'),
('ALL', 'Albanian Lek', 'L', 2, 'inactive'),
('AMD', 'Armenian Dram', '֏', 2, 'inactive'),
('ANG', 'Netherlands Antillean Guilder', 'ƒ', 2, 'inactive'),
('AOA', 'Angolan Kwanza', 'Kz', 2, 'inactive'),
('ARS', 'Argentine Peso', '$', 2, 'inactive'),
('AUD', 'Australian Dollar', 'A$', 2, 'inactive'),
('AWG', 'Aruban Florin', 'ƒ', 2, 'inactive'),
('AZN', 'Azerbaijani Manat', '₼', 2, 'inactive'),
('BAM', 'Bosnia and Herzegovina Convertible Mark', 'KM', 2, 'inactive'),
('BBD', 'Barbadian Dollar', 'Bds$', 2, 'inactive'),
('BDT', 'Bangladeshi Taka', '৳', 2, 'active'),
('BGN', 'Bulgarian Lev', 'лв', 2, 'inactive'),
('BHD', 'Bahraini Dinar', 'BD', 3, 'inactive'),
('BIF', 'Burundian Franc', 'FBu', 0, 'inactive'),
('BMD', 'Bermudian Dollar', 'BD$', 2, 'inactive'),
('BND', 'Brunei Dollar', 'B$', 2, 'inactive'),
('BOB', 'Bolivian Boliviano', 'Bs.', 2, 'inactive'),
('BRL', 'Brazilian Real', 'R$', 2, 'inactive'),
('BSD', 'Bahamian Dollar', 'B$', 2, 'inactive'),
('BTN', 'Bhutanese Ngultrum', 'Nu.', 2, 'inactive'),
('BWP', 'Botswana Pula', 'P', 2, 'inactive'),
('BYN', 'Belarusian Ruble', 'Br', 2, 'inactive'),
('BZD', 'Belize Dollar', 'BZ$', 2, 'inactive'),
('CAD', 'Canadian Dollar', 'C$', 2, 'inactive'),
('CDF', 'Congolese Franc', 'FC', 2, 'inactive'),
('CHF', 'Swiss Franc', 'CHF', 2, 'inactive'),
('CLP', 'Chilean Peso', '$', 0, 'inactive'),
('CNY', 'Chinese Yuan', '¥', 2, 'active'),
('COP', 'Colombian Peso', '$', 2, 'inactive'),
('CRC', 'Costa Rican Colon', '₡', 2, 'inactive'),
('CUP', 'Cuban Peso', '₱', 2, 'inactive'),
('CVE', 'Cape Verdean Escudo', 'Esc', 2, 'inactive'),
('CZK', 'Czech Koruna', 'Kč', 2, 'inactive'),
('DJF', 'Djiboutian Franc', 'Fdj', 0, 'inactive'),
('DKK', 'Danish Krone', 'kr', 2, 'inactive'),
('DOP', 'Dominican Peso', 'RD$', 2, 'inactive'),
('DZD', 'Algerian Dinar', 'DA', 2, 'inactive'),
('EGP', 'Egyptian Pound', 'E£', 2, 'inactive'),
('ERN', 'Eritrean Nakfa', 'Nfk', 2, 'inactive'),
('ETB', 'Ethiopian Birr', 'Br', 2, 'inactive'),
('EUR', 'Euro', '€', 2, 'active'),
('FJD', 'Fijian Dollar', 'FJ$', 2, 'inactive'),
('FKP', 'Falkland Islands Pound', '£', 2, 'inactive'),
('GBP', 'British Pound', '£', 2, 'active'),
('GEL', 'Georgian Lari', '₾', 2, 'inactive'),
('GHS', 'Ghanaian Cedi', 'GH₵', 2, 'inactive'),
('GIP', 'Gibraltar Pound', '£', 2, 'inactive'),
('GMD', 'Gambian Dalasi', 'D', 2, 'inactive'),
('GNF', 'Guinean Franc', 'FG', 0, 'inactive'),
('GTQ', 'Guatemalan Quetzal', 'Q', 2, 'inactive'),
('GYD', 'Guyanese Dollar', 'GY$', 2, 'inactive'),
('HKD', 'Hong Kong Dollar', 'HK$', 2, 'inactive'),
('HNL', 'Honduran Lempira', 'L', 2, 'inactive'),
('HRK', 'Croatian Kuna', 'kn', 2, 'inactive'),
('HTG', 'Haitian Gourde', 'G', 2, 'inactive'),
('HUF', 'Hungarian Forint', 'Ft', 2, 'inactive'),
('IDR', 'Indonesian Rupiah', 'Rp', 2, 'inactive'),
('ILS', 'Israeli New Shekel', '₪', 2, 'inactive'),
('INR', 'Indian Rupee', '₹', 2, 'active'),
('IQD', 'Iraqi Dinar', 'ID', 3, 'inactive'),
('IRR', 'Iranian Rial', '﷼', 2, 'inactive'),
('ISK', 'Icelandic Krona', 'kr', 0, 'inactive'),
('JMD', 'Jamaican Dollar', 'J$', 2, 'inactive'),
('JOD', 'Jordanian Dinar', 'JD', 3, 'inactive'),
('JPY', 'Japanese Yen', '¥', 0, 'active'),
('KES', 'Kenyan Shilling', 'KSh', 2, 'inactive'),
('KGS', 'Kyrgyzstani Som', 'сом', 2, 'inactive'),
('KHR', 'Cambodian Riel', '៛', 2, 'inactive'),
('KMF', 'Comorian Franc', 'CF', 0, 'inactive'),
('KPW', 'North Korean Won', '₩', 2, 'inactive'),
('KRW', 'South Korean Won', '₩', 0, 'inactive'),
('KWD', 'Kuwaiti Dinar', 'KD', 3, 'inactive'),
('KYD', 'Cayman Islands Dollar', '$', 2, 'inactive'),
('KZT', 'Kazakhstani Tenge', '₸', 2, 'inactive'),
('LAK', 'Lao Kip', '₭', 2, 'inactive'),
('LBP', 'Lebanese Pound', 'L.L.', 2, 'inactive'),
('LKR', 'Sri Lankan Rupee', 'Rs', 2, 'inactive'),
('LRD', 'Liberian Dollar', 'L$', 2, 'inactive'),
('LSL', 'Lesotho Loti', 'L', 2, 'inactive'),
('LYD', 'Libyan Dinar', 'LD', 3, 'inactive'),
('MAD', 'Moroccan Dirham', 'DH', 2, 'inactive'),
('MDL', 'Moldovan Leu', 'L', 2, 'inactive'),
('MGA', 'Malagasy Ariary', 'Ar', 2, 'inactive'),
('MKD', 'Macedonian Denar', 'den', 2, 'inactive'),
('MMK', 'Myanmar Kyat', 'K', 2, 'inactive'),
('MNT', 'Mongolian Togrog', '₮', 2, 'inactive'),
('MOP', 'Macanese Pataca', 'MOP$', 2, 'inactive'),
('MRU', 'Mauritanian Ouguiya', 'UM', 2, 'inactive'),
('MUR', 'Mauritian Rupee', '₨', 2, 'inactive'),
('MVR', 'Maldivian Rufiyaa', 'Rf', 2, 'inactive'),
('MWK', 'Malawian Kwacha', 'MK', 2, 'inactive'),
('MXN', 'Mexican Peso', '$', 2, 'inactive'),
('MYR', 'Malaysian Ringgit', 'RM', 2, 'inactive'),
('MZN', 'Mozambican Metical', 'MT', 2, 'inactive'),
('NAD', 'Namibian Dollar', 'N$', 2, 'inactive'),
('NGN', 'Nigerian Naira', '₦', 2, 'inactive'),
('NIO', 'Nicaraguan Cordoba', 'C$', 2, 'inactive'),
('NOK', 'Norwegian Krone', 'kr', 2, 'inactive'),
('NPR', 'Nepalese Rupee', 'रू', 2, 'inactive'),
('NZD', 'New Zealand Dollar', 'NZ$', 2, 'inactive'),
('OMR', 'Omani Rial', 'RO', 3, 'inactive'),
('PAB', 'Panamanian Balboa', 'B/.', 2, 'inactive'),
('PEN', 'Peruvian Sol', 'S/.', 2, 'inactive'),
('PGK', 'Papua New Guinean Kina', 'K', 2, 'inactive'),
('PHP', 'Philippine Peso', '₱', 2, 'inactive'),
('PKR', 'Pakistani Rupee', '₨', 2, 'inactive'),
('PLN', 'Polish Zloty', 'zł', 2, 'inactive'),
('PYG', 'Paraguayan Guarani', '₲', 0, 'inactive'),
('QAR', 'Qatari Riyal', 'QR', 2, 'inactive'),
('RON', 'Romanian Leu', 'lei', 2, 'inactive'),
('RSD', 'Serbian Dinar', 'din.', 2, 'inactive'),
('RUB', 'Russian Ruble', '₽', 2, 'inactive'),
('RWF', 'Rwandan Franc', 'RF', 0, 'inactive'),
('SAR', 'Saudi Riyal', '﷼', 2, 'inactive'),
('SBD', 'Solomon Islands Dollar', 'SI$', 2, 'inactive'),
('SCR', 'Seychellois Rupee', '₨', 2, 'inactive'),
('SDG', 'Sudanese Pound', 'SD', 2, 'inactive'),
('SEK', 'Swedish Krona', 'kr', 2, 'inactive'),
('SGD', 'Singapore Dollar', 'S$', 2, 'inactive'),
('SHP', 'Saint Helena Pound', '£', 2, 'inactive'),
('SLL', 'Sierra Leonean Leone', 'Le', 2, 'inactive'),
('SOS', 'Somali Shilling', 'Sh.So.', 2, 'inactive'),
('SRD', 'Surinamese Dollar', 'SRD$', 2, 'inactive'),
('SSP', 'South Sudanese Pound', '£', 2, 'inactive'),
('STN', 'Sao Tome and Principe Dobra', 'Db', 2, 'inactive'),
('SYP', 'Syrian Pound', 'LS', 2, 'inactive'),
('SZL', 'Eswatini Lilangeni', 'L', 2, 'inactive'),
('THB', 'Thai Baht', '฿', 2, 'inactive'),
('TJS', 'Tajikistani Somoni', 'SM', 2, 'inactive'),
('TMT', 'Turkmenistani Manat', 'T', 2, 'inactive'),
('TND', 'Tunisian Dinar', 'DT', 3, 'inactive'),
('TOP', 'Tongan Paʻanga', 'T$', 2, 'inactive'),
('TRY', 'Turkish Lira', '₺', 2, 'inactive'),
('TTD', 'Trinidad and Tobago Dollar', 'TT$', 2, 'inactive'),
('TWD', 'New Taiwan Dollar', 'NT$', 2, 'inactive'),
('TZS', 'Tanzanian Shilling', 'TSh', 2, 'inactive'),
('UAH', 'Ukrainian Hryvnia', '₴', 2, 'inactive'),
('UGX', 'Ugandan Shilling', 'USh', 0, 'inactive'),
('USD', 'US Dollar', '$', 2, 'active'),
('UYU', 'Uruguayan Peso', '$U', 2, 'inactive'),
('UZS', 'Uzbekistani Som', 'soum', 2, 'inactive'),
('VES', 'Venezuelan Bolivar', 'Bs.S', 2, 'inactive'),
('VND', 'Vietnamese Dong', '₫', 0, 'inactive'),
('VUV', 'Vanuatu Vatu', 'VT', 0, 'inactive'),
('WST', 'Samoan Tala', 'WS$', 2, 'inactive'),
('XAF', 'Central African CFA Franc', 'FCFA', 0, 'inactive'),
('XCD', 'East Caribbean Dollar', '$', 2, 'inactive'),
('XOF', 'West African CFA Franc', 'CFA', 0, 'inactive'),
('XPF', 'CFP Franc', 'F', 0, 'inactive'),
('YER', 'Yemeni Rial', 'YR', 2, 'inactive'),
('ZAR', 'South African Rand', 'R', 2, 'inactive'),
('ZMW', 'Zambian Kwacha', 'ZK', 2, 'inactive'),
('ZWL', 'Zimbabwean Dollar', 'Z$', 2, 'inactive');

-- Default exchange rates (base: USD)
INSERT INTO `op_exchange_rates` (`base_currency`, `target_currency`, `rate`, `source`) VALUES
('USD', 'USD', 1.00000000, 'manual'),
('USD', 'BDT', 117.50000000, 'manual'),
('USD', 'EUR', 0.92000000, 'manual'),
('USD', 'GBP', 0.78000000, 'manual'),
('USD', 'INR', 83.50000000, 'manual'),
('USD', 'JPY', 156.20000000, 'manual'),
('USD', 'CNY', 7.24000000, 'manual'),
('BDT', 'USD', 0.00851000, 'manual'),
('BDT', 'EUR', 0.00783000, 'manual'),
('BDT', 'GBP', 0.00664000, 'manual'),
('BDT', 'INR', 0.71060000, 'manual'),
('BDT', 'BDT', 1.00000000, 'manual');
