<?php
declare(strict_types=1);

namespace OwnPay\Controller\Admin;

use OwnPay\Container;
use OwnPay\Service\Admin\AdminSession;
use OwnPay\Http\Request;
use OwnPay\Http\Response;

/**
 * Device management — lists paired companion-app devices.
 *
 * DevicePairingService requires ENCRYPTION_KEY + JWT_SECRET in .env.
 * These are generated by the installer. If missing, page shows config warning.
 */
final class DeviceController
{
    use AdminPageTrait;

    private Container $c;
    private AdminSession $session;

    public function __construct(Container $c, AdminSession $session)
    {
        $this->c = $c;
        $this->session = $session;
    }

    private function getService(): ?\OwnPay\Service\Device\DevicePairingService
    {
        try {
            return $this->c->get(\OwnPay\Service\Device\DevicePairingService::class);
        } catch (\Throwable) {
            return null;
        }
    }

    public function index(Request $req): Response
    {
        $svc = $this->getService();
        if ($svc === null) {
            return $this->renderAdminPage('admin/devices/index.twig', [
                'devices'      => [],
                'stats'        => ['total' => 0, 'active' => 0, 'revoked' => 0],
                'active_page'  => 'devices',
                'config_error' => 'Device pairing requires ENCRYPTION_KEY and JWT_SECRET in your .env file. Run the installer or add them manually.',
            ]);
        }

        $brand = $this->c->get(\OwnPay\Service\Brand\BrandContext::class);
        $brand->resolveFromRequest($req);
        $mid = $brand->getActiveBrandId();

        $list = $svc->listDevices($mid);

        $stats = [
            'total'   => count($list),
            'active'  => count(array_filter($list, fn($d) => ($d['status'] ?? '') === 'active')),
            'revoked' => count(array_filter($list, fn($d) => ($d['status'] ?? '') === 'revoked')),
        ];

        return $this->renderAdminPage('admin/devices/index.twig', [
            'devices'     => $list,
            'stats'       => $stats,
            'active_page' => 'devices',
        ]);
    }

    /** POST /admin/devices/generate-otp — generate pairing code for mobile app */
    public function generateOtp(Request $req): Response
    {
        $svc = $this->getService();
        if ($svc === null) {
            return Response::json(['success' => false, 'error' => 'Device service not configured']);
        }

        $brand = $this->c->get(\OwnPay\Service\Brand\BrandContext::class);
        $brand->resolveFromRequest($req);
        $mid = $brand->getActiveBrandId();

        try {
            $result = $svc->generatePairingOtp($mid);
            return Response::json([
                'success'    => true,
                'otp'        => $result['otp'],
                'expires_in' => $result['expires_in'] ?? 300,
                'csrf_token' => \OwnPay\Security\SecurityHelpers::csrfToken(),
            ]);
        } catch (\Throwable $e) {
            return Response::json(['success' => false, 'error' => $e->getMessage()]);
        }
    }

    public function revoke(Request $req): Response
    {
        $svc = $this->getService();
        if ($svc === null) {
            $this->session->flashError('Device service not configured.');
            return Response::redirect('/admin/devices');
        }

        $uuid = (string) $req->param('id');
        $brand = $this->c->get(\OwnPay\Service\Brand\BrandContext::class);
        $brand->resolveFromRequest($req);
        $mid = $brand->getActiveBrandId();

        $svc->revoke($uuid, $mid);
        $this->session->flashSuccess('Device revoked');
        return Response::redirect('/admin/devices');
    }

    public function bulkRevoke(Request $req): Response
    {
        $svc = $this->getService();
        if ($svc === null) {
            $this->session->flashError('Device service not configured.');
            return Response::redirect('/admin/devices');
        }

        $brand = $this->c->get(\OwnPay\Service\Brand\BrandContext::class);
        $brand->resolveFromRequest($req);
        $mid = $brand->getActiveBrandId();

        $ids = $req->post('device_ids') ?? [];
        if (is_array($ids) && !empty($ids)) {
            foreach ($ids as $uuid) {
                $svc->revoke((string) $uuid, $mid);
            }
            $this->session->flashSuccess(count($ids) . ' devices revoked.');
        } else {
            $this->session->flashError('No devices selected.');
        }
        return Response::redirect('/admin/devices');
    }
}
