<?php
declare(strict_types=1);

namespace OwnPay\Controller\Admin;

use OwnPay\Container;
use OwnPay\Service\Admin\AdminSession;
use OwnPay\Http\Request;
use OwnPay\Http\Response;

/**
 * Device management â€” lists paired companion-app devices.
 *
 * DevicePairingService requires ENCRYPTION_KEY + JWT_SECRET in .env.
 * These are generated by the installer. If missing, page shows config warning.
 */
final class DeviceController
{
    use AdminPageTrait;

    private Container $c;
    private AdminSession $session;

    public function __construct(Container $c, AdminSession $session) { $this->c = $c;
        $this->session = $session; }

    private function getService(): ?\OwnPay\Service\Device\DevicePairingService
    {
        try {
            return $this->c->get(\OwnPay\Service\Device\DevicePairingService::class);
        } catch (\Throwable) {
            return null;
        }
    }

    public function index(Request $req): Response
    {
        $svc = $this->getService();
        if ($svc === null) {
            return $this->renderAdminPage('admin/devices/index.twig', [
                'devices' => [],
                'active_page' => 'devices',
                'config_error' => 'Device pairing requires ENCRYPTION_KEY and JWT_SECRET in your .env file. Run the installer or add them manually.',
            ]);
        }

        $brand = $this->c->get(\OwnPay\Service\Brand\BrandContext::class); $brand->resolveFromRequest($req); $mid = $brand->getActiveBrandId();
        $list = $svc->listDevices($mid);
        return $this->renderAdminPage('admin/devices/index.twig', ['devices' => $list, 'active_page' => 'devices']);
    }

    public function revoke(Request $req): Response
    {
        $svc = $this->getService();
        if ($svc === null) { $this->session->flashError('Device service not configured.'); return Response::redirect('/admin/devices'); }

        $uuid = (string) $req->param('id');
        $brand = $this->c->get(\OwnPay\Service\Brand\BrandContext::class); $brand->resolveFromRequest($req); $mid = $brand->getActiveBrandId();
        $svc->revoke($uuid, $mid);
        $this->session->flashSuccess('Device revoked');
        return Response::redirect('/admin/devices');
    }

    public function bulkRevoke(Request $req): Response
    {
        $svc = $this->getService();
        if ($svc === null) { $this->session->flashError('Device service not configured.'); return Response::redirect('/admin/devices'); }

        $brand = $this->c->get(\OwnPay\Service\Brand\BrandContext::class); $brand->resolveFromRequest($req); $mid = $brand->getActiveBrandId();
        $ids = $req->post('device_ids') ?? [];
        if (is_array($ids) && !empty($ids)) {
            foreach ($ids as $uuid) {
                $svc->revoke((string) $uuid, $mid);
            }
            $this->session->flashSuccess(count($ids) . ' devices revoked.');
        } else {
            $this->session->flashError('No devices selected.');
        }
        return Response::redirect('/admin/devices');
    }
}
