-- Ensure every system permission is available to Roles & Permissions.
-- INSERT IGNORE keeps this safe for existing installations and preserves
-- administrator-assigned role mappings.
INSERT IGNORE INTO `op_permissions` (`slug`, `name`, `group_name`) VALUES
('dashboard.view', 'View Dashboard', 'dashboard'),
('dashboard.stats', 'View Statistics', 'dashboard'),
('transactions.view', 'View Transactions', 'transactions'),
('transactions.manage', 'Manage Transactions', 'transactions'),
('transactions.update', 'Update Transactions', 'transactions'),
('transactions.export', 'Export Transactions', 'transactions'),
('invoices.view', 'View Invoices', 'invoices'),
('invoices.manage', 'Manage Invoices', 'invoices'),
('invoices.create', 'Create Invoices', 'invoices'),
('invoices.update', 'Update Invoices', 'invoices'),
('invoices.delete', 'Delete Invoices', 'invoices'),
('payment_links.view', 'View Payment Links', 'payment_links'),
('payment_links.manage', 'Manage Payment Links', 'payment_links'),
('payment_links.create', 'Create Payment Links', 'payment_links'),
('payment_links.update', 'Update Payment Links', 'payment_links'),
('payment_links.delete', 'Delete Payment Links', 'payment_links'),
('customers.view', 'View Customers', 'customers'),
('customers.manage', 'Manage Customers', 'customers'),
('customers.create', 'Create Customers', 'customers'),
('customers.update', 'Update Customers', 'customers'),
('gateways.view', 'View Gateways', 'gateways'),
('gateways.manage', 'Manage Gateways', 'gateways'),
('staff.view', 'View Staff', 'staff'),
('staff.manage', 'Manage Staff', 'staff'),
('staff.create', 'Create Staff', 'staff'),
('staff.update', 'Update Staff', 'staff'),
('staff.delete', 'Delete Staff', 'staff'),
('brands.view', 'View Brands', 'brands'),
('brands.manage', 'Manage Brands', 'brands'),
('brands.access_all', 'Access All Brands view', 'brands'),
('merchants.view', 'View Merchants', 'merchants'),
('merchants.create', 'Create Merchants', 'merchants'),
('merchants.update', 'Update Merchants', 'merchants'),
('settings.view', 'View Settings', 'settings'),
('settings.manage', 'Manage Settings', 'settings'),
('settings.update', 'Update Settings', 'settings'),
('api_keys.view', 'View API Keys', 'api_keys'),
('api_keys.manage', 'Manage API Keys', 'api_keys'),
('webhooks.view', 'View Webhooks', 'webhooks'),
('webhooks.manage', 'Manage Webhooks', 'webhooks'),
('domains.view', 'View Domains', 'domains'),
('domains.manage', 'Manage Domains', 'domains'),
('sms.view', 'View SMS Data', 'sms'),
('sms.manage', 'Manage SMS Templates', 'sms'),
('devices.view', 'View Devices', 'devices'),
('devices.manage', 'Manage Devices', 'devices'),
('plugins.view', 'View Plugins', 'plugins'),
('plugins.manage', 'Install/Remove Plugins', 'plugins'),
('system.update', 'System Updates', 'system'),
('system.audit', 'View Audit Log', 'system'),
('system.reports', 'View Reports', 'system'),
('system.balance', 'Balance Verification', 'system'),
('admin.access', 'Basic Admin Access', 'admin');
