-- Migration 007: Create Languages Table and staff language preferences
CREATE TABLE IF NOT EXISTS `op_languages` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `code` VARCHAR(10) NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    `status` ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
    `is_default` TINYINT(1) NOT NULL DEFAULT 0,
    `translations` LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_code` (`code`),
    CONSTRAINT `chk_translations_json` CHECK (json_valid(`translations`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `op_merchant_users` ADD COLUMN `language` VARCHAR(10) NULL DEFAULT NULL AFTER `two_factor_enabled`;

INSERT INTO `op_languages` (`code`, `name`, `status`, `is_default`, `translations`)
VALUES ('en', 'English', 'active', 1, '{
    "menu.dashboard": "Dashboard",
    "menu.payments": "Payments",
    "menu.transactions": "Transactions",
    "menu.invoices": "Invoices",
    "menu.payment_links": "Payment Links",
    "menu.ledger": "Ledger",
    "menu.disputes": "Disputes",
    "menu.gateways": "Gateways",
    "menu.payment_gateways": "Payment Gateways",
    "menu.currencies_rates": "Currencies & Rates",
    "menu.people": "People",
    "menu.brands": "Brands",
    "menu.customers": "Customers",
    "menu.staff": "Staff",
    "menu.roles_permissions": "Roles & Permissions",
    "menu.mobile_sms": "Mobile & SMS",
    "menu.paired_devices": "Paired Devices",
    "menu.sms_center": "SMS Center",
    "menu.sms_data": "SMS Data",
    "menu.reports_finance": "Reports & Finance",
    "menu.reports": "Reports",
    "menu.activities": "Audit Log",
    "menu.audit_log": "Audit Log",
    "menu.balance_verification": "Balance Verification",
    "menu.audit_integrity": "Audit Integrity",
    "menu.developers": "Developers",
    "menu.developer_hub": "Developer Hub",
    "menu.api_keys": "API Keys",
    "menu.webhooks_dlq": "Webhooks / DLQ",
    "menu.rate_limits": "Rate Limits",
    "menu.documentation": "Documentation",
    "menu.appearance": "Appearance",
    "menu.branding": "Branding",
    "menu.landing_page": "Landing Page",
    "menu.themes": "Themes",
    "menu.system": "System",
    "menu.plugins": "Plugins",
    "menu.addons": "Addons",
    "menu.domains": "Domains",
    "menu.settings": "Settings",
    "menu.system_update": "System Update",
    "menu.account": "Account",
    "menu.my_account": "My Account",
    "common.save": "Save Changes",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.create": "Create",
    "common.actions": "Actions",
    "common.status": "Status",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.pending": "Pending",
    "common.suspended": "Suspended",
    "common.search": "Search...",
    "common.filter": "Filter",
    "common.date": "Date",
    "common.amount": "Amount",
    "common.currency": "Currency",
    "common.description": "Description",
    "common.details": "Details",
    "common.loading": "Loading...",
    "common.no_data": "No records found",
    "common.yes": "Yes",
    "common.no": "No",
    "common.back": "Back",
    "dashboard.title": "Dashboard",
    "dashboard.sales_volume": "Sales Volume",
    "dashboard.net_revenue": "Net Revenue",
    "dashboard.successful_payments": "Successful Payments",
    "dashboard.active_refunds": "Active Refunds",
    "dashboard.recent_transactions": "Recent Transactions",
    "dashboard.view_all": "View All",
    "dashboard.weekly_overview": "Weekly Overview",
    "settings.title": "System Settings",
    "settings.tab_general": "General",
    "settings.tab_branding": "Branding",
    "settings.tab_landing": "Landing Page",
    "settings.tab_payment": "Payments",
    "settings.tab_checkout": "Checkout",
    "settings.tab_theme": "Themes",
    "settings.tab_cron": "Cron Jobs",
    "settings.tab_language": "Language",
    "settings.save_settings": "Save Settings",
    "language.title": "Language Settings",
    "language.select_default": "Select Default Language",
    "language.upload_json": "Upload Translation File",
    "language.manual_create": "Manually Add Language",
    "language.languages_list": "Available Languages",
    "language.code": "Language Code",
    "language.name": "Language Name",
    "language.is_default": "Default",
    "language.translate_strings": "Translate Strings",
    "language.upload_button": "Upload Language",
    "language.create_button": "Create Language",
    "language.search_keys": "Search translation keys...",
    "language.save_translations": "Save Translations",
    "language.success_save": "Translations saved successfully",
    "language.success_upload": "Language file uploaded successfully",
    "language.success_create": "Language created successfully",
    "language.confirm_delete": "Are you sure you want to delete this language?",
    "navbar.global_view": "Global View",
    "navbar.alerts": "Alerts",
    "navbar.toggle_theme": "Toggle theme",
    "navbar.logout": "Logout",
    "common.today": "Today",
    "common.last_7_days": "Last 7 Days",
    "common.last_30_days": "Last 30 Days",
    "common.all_time": "All Time",
    "dashboard.total_revenue": "Total Revenue",
    "common.completed": "Completed",
    "transaction.trx_id": "TRX ID",
    "customer.customer": "Customer",
    "common.gateway": "Gateway",
    "dashboard.no_transactions": "No transactions yet."
}');
